# Generated by Django 4.1.4 on 2022-12-11 00:06

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=cpf_field.models.CPFField(blank=True, max_length=14, null=True, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='user',
            name='perfil_img',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_img'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
