# Generated by Django 4.1.4 on 2022-12-11 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='250', upload_to='imagens/%Y/%m/%d', width_field='400')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'imagens',
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(verbose_name='descrição')),
                ('size', models.CharField(choices=[('P', 'pequeno'), ('M', 'médio'), ('G', 'grande'), ('GG', 'gigante'), ('XG', 'extra grande')], max_length=2)),
                ('id_image', models.ManyToManyField(db_column='id_imagens', to='home.image', verbose_name='imagens')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_Product', models.ManyToManyField(db_column='id_Product', to='home.product', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Product', models.ManyToManyField(db_column='id_Product', to='home.product', verbose_name='Products')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'carrinho',
                'verbose_name_plural': 'carrinhos',
                'db_table': 'carrinho',
            },
        ),
    ]
